version: '3.3'

services:
  database1:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hits-restaurant-aggregator-auth
      POSTGRES_USER: elena
      POSTGRES_PASSWORD: asd123
  database2:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hits-restaurant-aggregator
      POSTGRES_USER: elena
      POSTGRES_PASSWORD: asd123